---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "aqg-server"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "aqg-web-server"
  namespace: "aqg-server"
  labels:
    app: "aqg-web-server"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "aqg-web-server"
  template:
    metadata:
      labels:
        app: "aqg-web-server"
    spec:
      containers:
      - name: "aqg-onmt-1"
        image: "gnotnek013/aqg-onmt"
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "aqg-web-server-hpa-sgur"
  namespace: "aqg-server"
  labels:
    app: "aqg-web-server"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "aqg-web-server"
    apiVersion: "apps/v1"
  minReplicas: 3
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 80
