---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "aqg-gke"
  namespace: "default"
  labels:
    app: "aqg-gke"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "aqg-gke"
  template:
    metadata:
      labels:
        app: "aqg-gke"
    spec:
      containers:
      - name: "aqg-onmt-1"
        image: "gnotnek013/aqg-onmt:latest"
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "aqg-gke-hpa-fwzq"
  namespace: "default"
  labels:
    app: "aqg-gke"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "aqg-gke"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 80
