name: CI/CD Pipeline
on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    name: build and deliver artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag aqg-onmt
          
      - name: Login to Docker Image
        run: |
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Tag and Push Docker Images
        run: |
          docker tag aqg-onmt ${DOCKER_HUB_USERNAME}/aqg-onmt
          docker push ${DOCKER_HUB_USERNAME}/aqg-onmt
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: SSH into GCP VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.GCP_VM_IP }}
        username: ${{ secrets.GCP_VM_USERNAME }}
        key: ${{ secrets.GCP_VM_SSH_KEY }}

        script: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/aqg-onmt:latest
          docker stop aqg-onmt || true
          docker rm aqg-onmt || true
          docker run -d -p 5050:5050 --name aqg-onmt ${{ secrets.DOCKER_HUB_USERNAME }}/aqg-onmt:latest
