name: CI/CD Pipeline
on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: aqg-cluster2    # cluster name
  GKE_ZONE: asia-southeast2-a   # cluster zone

jobs:
  test:
    name: test code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install depentence
        run: |
          pip install -r requirements.txt
      
      - name: run the app
        run: |
          python app.py
          
      - name: test code
        run: |
          python test_app.py

  build:
    needs: test
    name: build and deliver artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag aqg-onmt
          
      - name: Login to Docker Image
        run: |
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Tag and Push Docker Images
        run: |
          docker tag aqg-onmt ${DOCKER_HUB_USERNAME}/aqg-onmt
          docker push ${DOCKER_HUB_USERNAME}/aqg-onmt
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
          
  deploy:
    name: deploy into GKE
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'

    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
    
    - name: Deploy
      run: |-
        kubectl apply -f deploy.yml
        kubectl get pods
